create schema if not exists service_d_error;

create table service_d_error.items (
  id bigint generated by default as identity primary key,
  name text not null
);

grant usage on schema service_d_error to anon;
grant select on all tables in schema service_d_error to anon;

-- Intentionally invalid for the Henosis v1 additive policy. This branch is
-- retained as live diagnostic proof that a native migration error reaches plan.
drop table service_d_error.items;
