create schema if not exists service_d;

create table service_d.items (
  id bigint generated by default as identity primary key,
  name text not null
);

grant usage on schema service_d to anon;
grant select on all tables in schema service_d to anon;
